### ISSUE TITLE
build.sh no longer working

### ISSUE THREAD

**Issue by icebal** [ravenschade/borgbackup_on_android#1]
Libacl no longer builds, as it is missing configure.ac. this stops borgbackup from compiling. Relevant errors below.
checking whether the C compiler works... no                                                                             configure: error: in `/home/Git/borgbackup_on_android/borg/acl-2.2.52':
configure: error: C compiler cannot create executables             See `config.log' for more details                                                                                       + make
                                       libtoolize -c `libtoolize -n -i >/dev/null 2>/dev/null && echo -i` -f                          libtoolize: putting auxiliary files in '.'.                        libtoolize: copying file './ltmain.sh'                                                                                  cp include/install-sh .                                                                                                 aclocal -I m4
                         aclocal: error: 'configure.ac' is required
           make: *** [Makefile:68: include/builddefs] Error 1
+ make install install-lib install-dev                             libtoolize -c `libtoolize -n -i >/dev/null 2>/dev/null && echo -i` -f                                                                 libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
cp include/install-sh .
aclocal -I m4
aclocal: error: 'configure.ac' is required
make: *** [Makefile:68: include/builddefs] Error 1

borg/platform_linux.c:483:10: fatal error: 'sys/acl.h' file not found
    #include "sys/acl.h"
             ^~~~~~~~~~~
    1 error generated.
    error: command 'aarch64-linux-android-clang' failed with exit status 1

    ----------------------------------------
Command "/home/Git/borgbackup_on_android/borg-env/bin/python3 -c "import setuptools, tokenize;__file__='/home/Git/borgbackup_on_android/borg/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/Git/borgbackup_on_android/borg/
+ cd ..
+ export BORG_RSH=borg_ssh_wrapper
+ BORG_RSH=borg_ssh_wrapper
+ cp borg_ssh_wrapper /data/data/com.termux/files/usr/bin/borg_ssh_wrapper
+ chmod +x /data/data/com.termux/files/usr/bin/borg_ssh_wrapper
+ borg init borg_test
./build.sh: line 81: borg: command not found
+ borg create borg_test::1 borg
./build.sh: line 82: borg: command not found
+ borg list borg_test
./build.sh: line 83: borg: command not found
+ borg info borg_test::1
./build.sh: line 84: borg: command not found
+ borg list borg_test::1
./build.sh: line 85: borg: command not found
$

**Comment by ravenschade** [comment]
Which Termux version and Android version are you using?

**Comment by icebal** [comment]
7.1.1 and the latest termux. Its not looking like a version issue, it looks like the src the script is grabbing is bad/packaged wrong.

**Comment by ravenschade** [comment]
I am wondering why you get "configure: error: C compiler cannot create executables". Can you please check you installed clang version (clang --version), please?

**Comment by icebal** [comment]
clang --version
clang version 5.0.0 (tags/RELEASE_500/final)
Target: aarch64--linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin

**Comment by icebal** [comment]
Config.log output:
configure:2737: checking whether the C compiler works
configure:2759: clang   -lintl conftest.c  >&5
/data/data/com.termux/files/usr/bin/ld: cannot find -lintl
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
configure:2763: $? = 1
configure:2801: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:2806: error: in `/data/data/com.termux/files/home/Git/borgbackup_on_android/acl-2.2.52':
configure:2808: error: C compiler cannot create executables
See `config.log' for more details

**Comment by icebal** [comment]
Removed LDFLAGS=-lintl in build-sh allows it to go farther but then i run into a permission denied on '/data/data/com.termux/files/usr/include/lz4.h'

Permissions are rwrr and owned by my termux user

**Comment by icebal** [comment]
Fix the permissions issue, removing LDFLAGS=-lintl makes it all work :) this is for both libattr and libacl

**Comment by ravenschade** [comment]
Thank for the fix! 
I have tested it on a Nexus 6P with Android 8.
