### ISSUE TITLE
lock timeout

### ISSUE THREAD

**Issue by icebal** [ravenschade/borgbackup_on_android#3]
Currently getting the below error now. I have blown the folder away and let it recreate with proper permissions and still is not working. doing this in termux-choot btw.

Failed to create/acquire the lock /home/.cache/borg/62cd6172a3a10061f1a7298357d23921a909333703d81fe4962f33102cd69036/lock.exclusive (timeout).

**Comment by ravenschade** [comment]
You home directory within termux should be /data/data/com.termux/files/home/ and not /home. As /home does not exist on android, you get the above error. Please check the setting of your home directory with "env | grep HOME".
