### ISSUE TITLE
Update to borg 1.1

### ISSUE THREAD

**Issue by Findus23** [ravenschade/borgbackup_on_android#4]
First of all many thanks for your work. Before I was using borg on a folder mounted via go-mtp but that didn't work that well and needed to copy all files via USB on every run. With borg running on the phone it's by far faster.

I just tried if borg 1.1 is also working, but I am running into an error. What I did:
- `git checkout 1.1.2`
- reapply diff (a bit modified; see below)
- `pip install -e .`

But on every run borg is showing this error:
```
(borg-env) bash-4.4$ borg --version
WARNING: linker: /data/data/com.termux/files/usr/lib/libacl.so.1.1.0: unused DT entry: type 0xf arg 0x453
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg-env/bin/borg", line 11, in <module>
    load_entry_point('borgbackup', 'console_scripts', 'borg')()
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2749, in load_entry_point
    return ep.load()
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2402, in load
    return self.resolve()
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg/src/borg/archiver.py", line 38, in <module>
    from .archive import Archive, ArchiveChecker, ArchiveRecreater, Statistics, is_special
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg/src/borg/archive.py", line 24, in <module>
    from .cache import ChunkListEntry
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg/src/borg/cache.py", line 30, in <module>
    from .crypto.key import PlaintextKey
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg/src/borg/crypto/key.py", line 28, in <module>
    from ..platform import SaveFile
  File "/data/data/com.termux/files/home/borgbackup_on_android/borg/src/borg/platform/__init__.py", line 21, in <module>
    from .linux import API_VERSION as OS_API_VERSION
ImportError: dlopen failed: cannot locate symbol "sync_file_range" referenced by "/data/data/com.termux/files/home/borgbackup_on_android/borg/src/borg/platform/linux.cpython-36m.so"...
```
Any ideas what could cause this?

System information:

|                 |                   |
|-----------------|-------------------|
| Device          | Oneplus 3T        |
| Android version | 7.1.2 (LineageOS) |
| Termux version  | 0.54              |

----------
```diff
diff --git a/setup.py b/setup.py
index 42b27261..9a71aecc 100644
--- a/setup.py
+++ b/setup.py
@@ -161,7 +161,7 @@ def detect_libb2(prefixes):
 crypto_libraries = ['crypto']
 
 possible_openssl_prefixes = ['/usr', '/usr/local', '/usr/local/opt/openssl', '/usr/local/ssl', '/usr/local/openssl',
-                             '/usr/local/borg', '/opt/local', '/opt/pkg', ]
+                             '/usr/local/borg', '/opt/local', '/opt/pkg', '/data/data/com.termux/files/usr/']
 if os.environ.get('BORG_OPENSSL_PREFIX'):
     possible_openssl_prefixes.insert(0, os.environ.get('BORG_OPENSSL_PREFIX'))
 ssl_prefix = detect_openssl(possible_openssl_prefixes)
@@ -172,7 +172,7 @@ def detect_libb2(prefixes):
 
 
 possible_lz4_prefixes = ['/usr', '/usr/local', '/usr/local/opt/lz4', '/usr/local/lz4',
-                         '/usr/local/borg', '/opt/local', '/opt/pkg', ]
+                         '/usr/local/borg', '/opt/local', '/opt/pkg', '/data/data/com.termux/files/usr/' ]
 if os.environ.get('BORG_LZ4_PREFIX'):
     possible_lz4_prefixes.insert(0, os.environ.get('BORG_LZ4_PREFIX'))
 lz4_prefix = detect_lz4(possible_lz4_prefixes)
```

**Comment by ravenschade** [comment]
The main issue is 
 `ImportError: dlopen failed: cannot locate symbol "sync_file_range" referenced by "/data/data/com.termux/files/home/borgbackup_on_android/borg/src/borg/platform/linux.cpython-36m.so"...`

sync_file_range is used by borg in src/borg/platform/linux.pyx (https://github.com/borgbackup/borg/blob/8909ffc71a9fa737deaea230d5c310a18f5982a4/src/borg/platform/linux.pyx). 

I have updated borg to version 1.1 (branch 1.1-maint of https://github.com/borgbackup/borg) and tried a full reinstall on two devices (Nexus6p Android 8.0.0 and n7100 with Lineage 14.1 (7.1.1)). Android 8 works, but on Lineage 14.1 I encounter the same problem.

I suspect that sync_file_range is missing in this Lineage version. It was added to bionic only 1 year and 8 months ago: https://android.googlesource.com/platform/bionic/+log/master/libc/bionic/sync_file_range.cpp

sync_file_range.cpp does not exist in cm-14.1 branch of lineage (https://github.com/LineageOS/android_bionic/tree/cm-14.1/libc/bionic)

sync_file_range.cpp does exist in lineage-15.0 branch of lineage (https://github.com/LineageOS/android_bionic/tree/lineage-15.0/libc/bionic)

A workaround would be to find out, why borg 1.0.13 works, but borg 1.1.2 does not.

**Comment by ravenschade** [comment]
sync_file_range was added to borg by https://github.com/borgbackup/borg/pull/985 and already caused problems for the linux subsystem of windows 10 (https://github.com/borgbackup/borg/issues/1961).

**Comment by ravenschade** [comment]
I have added a test to the build script to detect sync_file_range. If it is not available, it will apply a patch to borg that replaces sync_file_range with a normal sync.

**Comment by Findus23** [comment]
Many thanks for the quick response.
Your solution seems to be working fine for me.
